### PR TITLE
Deserialization Issue

### PR DESCRIPTION
**Pull request by StriderDM**
Reverted changes for PR #15
Modified test to better illustrate the issue.

### CODE REVIEW

**Comment by h4sh3d** [comment]
I'm currently looking in more details what's going on. You right that the first fix is not necessary and the problem comes from the transaction parsing.

This test passes by adding the `RctSig` by hand and fail without it

```rust
// block with only the miner tx and no other transactions
let hex = "0c0c94debaf805beb3489c722a285c092a32e7c6893abfc7d069699c8326fc3445a749c5276b6200000000029b892201ffdf882201b699d4c8b1ec020223df524af2a2ef5f870adb6e1ceb03a475c39f8b9ef76aa50b46ddd2a18349402b012839bfa19b7524ec7488917714c216ca254b38ed0424ca65ae828a7c006aeaf10208f5316a7f6b99cca60000";

let bytes = hex::decode(hex).unwrap();
let mut block = deserialize::<Block>(&bytes[..]).unwrap();

// problem illustrated here
block.miner_tx.rct_signatures = RctSig {
    // sig: None is current deserialization
    sig: Option::from(RctSigBase {
        rct_type: RctType::Null,
        txn_fee: Default::default(),
        pseudo_outs: vec![],
        ecdh_info: vec![],
        out_pk: vec![],
    }),
    p: None,
};

println!("{:#?}", block);

let bytes2 = serialize::<Block>(&block);
let block2 = deserialize::<Block>(&bytes2[..]).unwrap();

println!("{:#?}", block2);

assert_eq!(bytes, bytes2);
```
I suspect that the problem comes from here https://github.com/monero-rs/monero-rs/blob/master/src/util/ringct.rs#L276, and might be the same for prunable one.

Can you create transaction tests that illustrate this, so I can fix and publish the fix?

**Comment by SWvheerden** [comment]
The fix I pushed in pr #15   look it breaks it, not even is not necessary

**Comment by StriderDM** [comment]
@h4sh3d 

I have pushed the extra transaction tests as requested.

I think you are right as to where the problem is coming from, looks like https://github.com/monero-rs/monero-rs/blob/master/src/util/ringct.rs#L276 needs to be this?

```
RctType::Null => Ok(Some(RctSigBase {
        rct_type: RctType::Null,
        txn_fee: Default::default(),
        pseudo_outs: vec![],
        ecdh_info: vec![],
        out_pk: vec![]
    })),
```

**Comment by h4sh3d** [comment]
Thanks, I'll merge that and fix on master

**Pull request merged**
