### PR TITLE
Fix extra field

### LINKED ISSUE #122: (de)serialization of transactions with certain data in the ExtraField fail
#### (de)serialization of transactions with MergeMining in the ExtraField fail because Monero encodes the size of the field 

https://github.com/monero-project/monero/blob/fc907a957078cae2dc68348886a33363848dd089/src/cryptonote_basic/tx_extra.h#L179

some examples of these transactions: 
 [36817336e72ecf7adcff92815de96a0893c1ef777701f1386ebce5f7d9272151](https://xmrchain.net/tx/36817336e72ecf7adcff92815de96a0893c1ef777701f1386ebce5f7d9272151/1)
[8b1daf9c85520ceee2e9ae5f7e66f9e72d1967f5c537180887865fb21fffbb45](https://xmrchain.net/tx/8b1daf9c85520ceee2e9ae5f7e66f9e72d1967f5c537180887865fb21fffbb45)
[1323c9e102253577690d75f8f77872ffada1c63c96dd3156330896d6e40207b2](https://xmrchain.net/tx/1323c9e102253577690d75f8f77872ffada1c63c96dd3156330896d6e40207b2/1)

#### (de)serialization of transactions with MysteriousMinerGate fail for the same reason and because it shouldn't be a string 

this is the raw hex of a transaction with MysteriousMinerGate in the ExtraField:
 
>0100010280d0b8e1981a0395c4028af209fbe5094003ffe9bac5274fbc8866f05980b94b5f5bc4890772781264bf1088c78b71b7038088aca3cf02023284697f8996723c43b382b9ea5f735d0caafbfefdaa82649c221f6c7f3a78be80c0ee8ed20b0239597ace027e669b08ef5b68d2b1471aa1419c5631bb7254276e54749c6ee4b380c0ee8ed20b02265c7d46eaca5934a18ffd284c8602a1d2f26aaae800fd67b4b67ce6be2057f84301ecc10bf24fb08a5b0a4054946148fb2de46398c2f6e3f1cac6d91ab0ed101489de20cfb23397ecf3fa3565e7c84ab5a858c05c78d524937d35fd5a05a41fba7d321033bd9400e123f51de5a683fe4ca8e6a498240504b2cadca32e77175135679c0a75ec30ca4caaa5a96513f57934672ab7905e86d65ee05f27bd07932be1cca002433b8ad4896ee976d86a057f195efc4a5f0599087ed0ad3a53bab3ba201daf004e77b37000f1bcb4b25416a2708b209ae538859a93e7756f8ee6a19c48aab8024c25b4b9fb7d4936b449ee119db7f7dfafa10298bfa9249bfd28a9b6a2d49705829db31c6bfd68c2716f52da2891715d79ffe0962d6aa6f14329b0e6fa3ceb07
 
~~#### (de)serialization of transactions with AdditionalPublickKeys fail because the field should just be PublicKey not a Vec
example of a transaction with AdditionalPublickKeys:
[23fbc9f5b8ac1b6f896756c4a1382658daf1e8d371c1e01c5baf66c1fbaf39bd](https://xmrchain.net/tx/23fbc9f5b8ac1b6f896756c4a1382658daf1e8d371c1e01c5baf66c1fbaf39bd/1)~~

although these errors can be fixed, as far as I know the extra field is a "free zone" for wallets to put whatever data they want. So I think it would be better to not error if the transactions extra field can't be de-serialized and instead just return the extra field raw.

### PR DESCRIPTION
**Pull request by Boog900**
fixes #122 

I have made it so de-serialization of the extra field will always return the raw extra field and it will try to parse it, instead of failing if it cannot be parsed.

### CODE REVIEW

**Comment by Boog900** [comment]
I have scanned every [pruned transaction](https://github.com/Boog900/monero-rs/blob/3e1ed9b7a458bed7c9e5d38b3775da0b26ad797e/src/database_types/transaction.rs#L33) up to block 2511915 using these changes and these are the only transactions where the extra field isn't fully parsed:

// Error parsing tx-extra: 4698003, e87c675a85f34ecac58a8846613d25062f1813e1023c552b705afad32b972c38
// Error parsing tx-extra: 4698192, 1431a2e30c2b2329f2704746be99f82833e7a49732f649e7397f7a7c48658166
// Error parsing tx-extra: 4839480, e5f0c0b1c482e036b8aa2a8cce3e6956a0a9959c0ee1304e28fbd40ca221efca
// Error parsing tx-extra: 4928129, f0d02eddf03cf332c8d97f0cf3ef1f809c8c3c7d8d129d52eddd68bbcc538da5
// Error parsing tx-extra: 4999805, d8c09f062ecbb35182f8043e884b1c7c10b44be097fa62dd966fe1d9a2c48490
// Error parsing tx-extra: 8157279, f6cff1edd1a7861ed13d494dd4ae7c4a7f42b5c3bf91457310d2166722c1316f
// Error parsing tx-extra: 8157377, 5f06fae0a7bdcb420bfa1714d3f702cf5d0b3ecc8385de736ebbec9b361ccf24
// Error parsing tx-extra: 8373697, d591ddfbbf248ba0bd952e37618ce947c0000b84d68dcc7b2fbda41897165408
// Error parsing tx-extra: 8157279, f6cff1edd1a7861ed13d494dd4ae7c4a7f42b5c3bf91457310d2166722c1316f
// Error parsing tx-extra: 8157377, 5f06fae0a7bdcb420bfa1714d3f702cf5d0b3ecc8385de736ebbec9b361ccf24
// Error parsing tx-extra: 8373697, d591ddfbbf248ba0bd952e37618ce947c0000b84d68dcc7b2fbda41897165408

 *note no transactions actually returned an error due to the extra field however some had invalid points: #124

**Review by h4sh3d — APPROVED** [review]

**Comment by Boog900** [comment]
I have scanned the blockchain up to 2769971 and here are some more transaction where the extra field is not fully parsed :

// Error parsing tx-extra: 0x68de…09a3, height: 1761365
// Error parsing tx-extra: 0xe3ce…d128, height: 1776617
// Error parsing tx-extra: 0x68fa…830c, height: 1785318
// Error parsing tx-extra: 0x4f56…b66b, height: 2134230
// Error parsing tx-extra: 0x504f…e67f, height: 2712581
// Error parsing tx-extra: 0x7acf…b219, height: 2742099

I think this is good to go now

**Comment by Boog900** [comment]
@vorot93  yeah good point, I think I might add some methods on the extra field to build from bytes and to build from sub fields to make it easier for people to build txs.

**Comment by vorot93** [comment]
Depends on #136

**Review by h4sh3d — APPROVED** [review]

**Pull request merged**
