### PR TITLE
Amount field is public

### PR DESCRIPTION
**Pull request by xmrbox**

### CODE REVIEW

**Comment by h4sh3d** [comment]
The inner value of `Amount` must not be public. The public API of `Amount` should guarantee that the inner value is correct.

**Comment by xmrbox** [comment]
Hi,

If we want to use this from another crate how do we call the constructor?

`monero::util::amount::Amount(100000000);
                      ^^^^^^ private tuple struct constructor`

**Comment by h4sh3d** [comment]
https://github.com/monero-rs/monero-rs/blob/main/src/util/amount.rs#L249

**Comment by xmrbox** [comment]
Thank you.

**Pull request closed without merging**
